3 agregar home screen
scesi/cappuchino-android pull request #7
Opened 2024-11-02 21:30 UTC by MauriNestor

2024-11-02 23:35 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +//            .background(Color.Gray)
Do not commit comments without explanation, leave an explanation or delete it

2024-11-02 23:36 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +//                .background(Color.Cyan)
Do not commit comments without explanation, leave an explanation or delete it

2024-11-02 23:37 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +            text = "Ponte comodo y arma tu horario con un cappuchino",
Dont use raw strings, instead use string resources , extract it (option + enter)

2024-11-02 23:37 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +            contentDescription = "descrip",
Dont use raw strings, instead use string resources , extract it (option + enter)

2024-11-02 23:37 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +        placeholder = { Text("Busca tu carrera", fontSize = 10.sp) },
Dont use raw strings, instead use string resources , extract it (option + enter)

2024-11-02 23:38 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +                contentDescription = "Buscar",
Dont use raw strings, instead use string resources , extract it (option + enter)

2024-11-02 23:38 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/screens/homeScreen.kt
> +//            .background(Color.Yellow)
Same with comments

2024-11-02 23:39 UTC, beldier commented on app/src/main/java/org/scesi/cappuchino/ui/Cappuchino.kt
> +fun CappuchinoScreen(content: @Composable ()->Unit){
format code  (option + command + L )

2024-11-02 23:40 UTC, beldier commented
@MauriNestor  please take a look at the comments

2024-11-03 22:19 UTC, MauriNestor commented
I think all the comments has been resolved.

2024-11-04 01:27 UTC, MauriNestor commented on app/src/main/java/org/scesi/cappuchino/ui/Cappuchino.kt
> +fun CappuchinoScreen(content: @Composable ()->Unit){
done @beldier

2024-11-04 01:29 UTC, beldier requested changes
- Fix font size 
 - Make the list scrollable 
 - Correct the page message

2024-11-05 04:32 UTC, MauriNestor commented
> * Fix font size
> * Make the list scrollable
> * Correct the page message 

all the comments corrected @beldier

2024-11-09 04:35 UTC, MauriNestor commented
@beldier I did preview, content and homeScreen funtion and also used dimens instead of magic numbers

2024-11-10 13:44 UTC, beldier approved these changes

2024-11-10 21:04 UTC, merged