4 agregar screen del about
scesi/cappuchino-android pull request #9
Opened 2024-11-07 22:49 UTC by geeklive123

subiendo cambio de rama about

2024-11-16 21:07 UTC, MauriNestor commented
it still doesn't implement this structure 
![image](https://github.com/user-attachments/assets/8b88268f-0a8e-4671-80bd-ad15a09cf82a)

2024-11-16 21:12 UTC, MauriNestor requested changes
please check the suggestions I made

2024-11-16 21:12 UTC, MauriNestor commented on app/src/main/java/org/scesi/cappuchino/ui/screens/About.kt
> +                text = "CONOCE MÁS SOBRE CAPPUCHINO",
don't use static text, instead of use file strings.xml

2024-11-16 21:12 UTC, MauriNestor commented on app/src/main/java/org/scesi/cappuchino/ui/screens/About.kt
> +                text = "Cappuchino es un sistema que facilita la gestión de horarios a los estudiantes de la Facultad de Ciencias y Tecnología de la Universidad Mayor de San Simón.",
don't use static text, instead of use file strings.xml

2024-11-16 21:12 UTC, MauriNestor commented on app/src/main/java/org/scesi/cappuchino/ui/screens/About.kt
> +            modifier = Modifier.padding(16.dp)
don't use magic numbers, use file dimens.xml
![image](https://github.com/user-attachments/assets/6809d19b-eb1c-4ad2-8236-d48a3ffc3900)
 you can create your own dimens

2024-11-26 02:03 UTC, beldier approved these changes

2024-11-26 02:05 UTC, beldier commented
@MauriNestor code is already fixed, please review it

2024-11-26 22:13 UTC, MauriNestor approved these changes

2024-11-29 00:40 UTC, merged